"""
code_review_agent.py — LLM-powered PR code reviewer.

Reads the PR diff and project grounding context (pyproject.toml, config.py,
dvc.yaml), then calls an LLM to produce a structured review covering:

  - Critical issues (API version mismatches, security, data leakage)
  - Warnings (style violations, missing DVC deps, workflow permission scope)
  - Suggestions (improvements, doc gaps)

Outputs a GitHub-flavoured markdown comment ready to post on the PR.

Usage:
    python code_review_agent.py \\
        --diff /tmp/pr_diff.txt \\
        --context /tmp/context.txt \\
        --output /tmp/review.md
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# llm_client lives in the same directory
sys.path.insert(0, str(Path(__file__).parent))
import llm_client  # noqa: E402

# --------------------------------------------------------------------------- #
# Prompts
# --------------------------------------------------------------------------- #
SYSTEM_PROMPT = """
You are a senior MLOps engineer performing a code review for a Python project.

Project facts (provided in the user message):
  - Dependency versions are pinned in pyproject.toml — these are AUTHORITATIVE.
  - DVC manages data and model artifacts; dvc.yaml defines the pipeline DAG.
  - src/config.py is the single source of truth for all paths and constants.
  - GitHub Actions workflows run inside Docker containers with a bind-mounted
    workspace; DVC-tracked files are NOT available via git checkout alone.

Your review must cover:
  1. API calls that are INCOMPATIBLE with the pinned library versions.
  2. Missing 'dvc pull' or 'dvc repro' before artifact-dependent script calls.
  3. Values hardcoded outside src/config.py that should be centralised.
  4. Secrets or credentials that could be leaked into logs.
  5. GitHub Actions permissions broader than necessary.
  6. DVC stages missing deps/outs declarations.
  7. General correctness, maintainability, and MLOps best practices.

Output format — use EXACTLY this markdown structure, no preamble:

## 🤖 Agent Code Review

### 🔴 Critical
<!-- List blocking issues. If none, write "None." -->

### ⚠️ Warnings
<!-- List non-blocking concerns. If none, write "None." -->

### 💡 Suggestions
<!-- Optional improvements. If none, write "None." -->

---
*Generated by agent-code-review. To re-run: Actions → Agent — Code Review → Run workflow.*

Be concise. Maximum 700 words total. No introductory sentences before the heading.
""".strip()


def build_user_prompt(diff: str, context: str) -> str:
    diff_preview = diff[:8000] if len(diff) > 8000 else diff
    ctx_preview = context[:4000] if len(context) > 4000 else context
    return (
        "=== PROJECT CONTEXT (pyproject.toml + config.py + dvc.yaml) ===\n"
        f"{ctx_preview}\n\n"
        "=== PR DIFF (Python and YAML files only) ===\n"
        f"{diff_preview}\n"
    )


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
def main() -> int:
    parser = argparse.ArgumentParser(description="LLM code review agent")
    parser.add_argument("--diff", required=True, type=Path)
    parser.add_argument("--context", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--local", action="store_true", default=False,
                        help="Prefer local Ollama over Gemini API")
    args = parser.parse_args()

    diff = args.diff.read_text(encoding="utf-8", errors="replace")
    context = args.context.read_text(encoding="utf-8", errors="replace")

    if not diff.strip():
        review = (
            "## 🤖 Agent Code Review\n\n"
            "No Python or YAML changes detected in this PR — nothing to review.\n"
        )
        args.output.write_text(review, encoding="utf-8")
        print(review)
        return 0

    prompt = build_user_prompt(diff, context)
    print("[code_review_agent] Calling LLM...", file=sys.stderr)
    review = llm_client.call(prompt, system=SYSTEM_PROMPT, prefer_local=args.local)

    args.output.write_text(review, encoding="utf-8")
    print(review)
    return 0


if __name__ == "__main__":
    sys.exit(main())
